-- 阅读器模块表注释与字段注释升级脚本
-- 适用时间：2026-08-15
-- 作用：补齐 reader 模块核心业务表的表注释与字段注释

ALTER TABLE reader_work COMMENT = '阅读器作品主表';
ALTER TABLE reader_work
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '作品ID',
  MODIFY COLUMN work_type VARCHAR(16) NOT NULL COMMENT '作品类型：NOVEL小说、COMIC漫画',
  MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '作品标题',
  MODIFY COLUMN intro TEXT NULL COMMENT '作品简介',
  MODIFY COLUMN cover_url VARCHAR(500) NULL COMMENT '作品封面地址',
  MODIFY COLUMN serial_status VARCHAR(32) NOT NULL DEFAULT 'ONGOING' COMMENT '连载状态：ONGOING连载中、FINISHED已完结',
  MODIFY COLUMN publish_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '发布状态：DRAFT草稿、PUBLISHED已上架、OFFLINE已下架',
  MODIFY COLUMN source_type VARCHAR(32) NOT NULL DEFAULT 'IMPORT' COMMENT '内容来源：IMPORT文件导入、SYNC授权同步',
  MODIFY COLUMN total_chapters INT NOT NULL DEFAULT 0 COMMENT '总章节数',
  MODIFY COLUMN total_pages INT NOT NULL DEFAULT 0 COMMENT '总页数，主要用于漫画',
  MODIFY COLUMN allow_search CHAR(1) NOT NULL DEFAULT '1' COMMENT '是否允许搜索：1允许、0禁止',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE reader_novel_chapter COMMENT = '小说章节表';
ALTER TABLE reader_novel_chapter
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '小说章节ID',
  MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '所属作品ID',
  MODIFY COLUMN volume_name VARCHAR(255) NULL COMMENT '卷名',
  MODIFY COLUMN chapter_name VARCHAR(255) NOT NULL COMMENT '章节标题',
  MODIFY COLUMN chapter_no INT NOT NULL DEFAULT 0 COMMENT '章节序号',
  MODIFY COLUMN word_count INT NOT NULL DEFAULT 0 COMMENT '章节字数',
  MODIFY COLUMN publish_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '发布状态：DRAFT草稿、PUBLISHED已发布、OFFLINE已下架',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';

CREATE TABLE IF NOT EXISTS reader_novel_chapter_content (
  chapter_id BIGINT PRIMARY KEY COMMENT '章节ID',
  content LONGTEXT NULL COMMENT '章节正文'
) COMMENT = '小说章节正文表';

ALTER TABLE reader_comic_chapter COMMENT = '漫画章节表';
ALTER TABLE reader_comic_chapter
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '漫画章节ID',
  MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '所属作品ID',
  MODIFY COLUMN chapter_name VARCHAR(255) NOT NULL COMMENT '章节标题',
  MODIFY COLUMN chapter_no INT NOT NULL DEFAULT 0 COMMENT '章节序号',
  MODIFY COLUMN page_count INT NOT NULL DEFAULT 0 COMMENT '章节页数',
  MODIFY COLUMN publish_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '发布状态：DRAFT草稿、PUBLISHED已发布、OFFLINE已下架',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE reader_comic_page COMMENT = '漫画分页表';
ALTER TABLE reader_comic_page
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '漫画页ID',
  MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '所属漫画章节ID',
  MODIFY COLUMN page_no INT NOT NULL DEFAULT 0 COMMENT '页序号',
  MODIFY COLUMN image_url VARCHAR(500) NOT NULL COMMENT '图片地址',
  MODIFY COLUMN width INT NULL COMMENT '图片宽度',
  MODIFY COLUMN height INT NULL COMMENT '图片高度',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE reader_import_task COMMENT = '导入任务主表';
ALTER TABLE reader_import_task
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '导入任务ID',
  MODIFY COLUMN task_name VARCHAR(255) NOT NULL COMMENT '任务名称',
  MODIFY COLUMN content_type VARCHAR(16) NOT NULL COMMENT '内容类型：NOVEL小说、COMIC漫画',
  MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '任务状态：CREATED已创建、PARSING解析中、PENDING_REVIEW待审核、PARSE_FAILED解析失败',
  MODIFY COLUMN oss_id BIGINT NULL COMMENT '关联OSS文件ID',
  MODIFY COLUMN total_units INT NOT NULL DEFAULT 0 COMMENT '总处理单元数',
  MODIFY COLUMN processed_units INT NOT NULL DEFAULT 0 COMMENT '已处理单元数',
  MODIFY COLUMN progress_percent INT NOT NULL DEFAULT 0 COMMENT '处理进度百分比',
  MODIFY COLUMN progress_message VARCHAR(255) NULL COMMENT '进度说明',
  MODIFY COLUMN fail_reason VARCHAR(1000) NULL COMMENT '失败原因',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE reader_import_file COMMENT = '导入文件记录表';
ALTER TABLE reader_import_file
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '导入文件记录ID',
  MODIFY COLUMN task_id BIGINT NOT NULL COMMENT '所属导入任务ID',
  MODIFY COLUMN origin_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
  MODIFY COLUMN file_suffix VARCHAR(32) NOT NULL COMMENT '文件后缀',
  MODIFY COLUMN oss_id BIGINT NULL COMMENT '关联OSS文件ID',
  MODIFY COLUMN file_size BIGINT NULL COMMENT '文件大小，单位字节',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE reader_content_audit COMMENT = '内容审核记录表';
ALTER TABLE reader_content_audit
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '审核记录ID',
  MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '所属作品ID',
  MODIFY COLUMN audit_status VARCHAR(32) NOT NULL COMMENT '审核状态：PENDING待审核、APPROVED已通过、REJECTED已驳回',
  MODIFY COLUMN audit_comment VARCHAR(1000) NULL COMMENT '审核意见',
  MODIFY COLUMN auditor_id BIGINT NULL COMMENT '审核人ID',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE reader_bookshelf COMMENT = '用户书架表';
ALTER TABLE reader_bookshelf
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '书架记录ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '作品ID',
  MODIFY COLUMN top_pin CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否置顶：1置顶、0不置顶',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE reader_reading_history COMMENT = '阅读历史表';
ALTER TABLE reader_reading_history
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '阅读历史ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '作品ID',
  MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '章节ID',
  MODIFY COLUMN content_type VARCHAR(16) NOT NULL COMMENT '内容类型：NOVEL小说、COMIC漫画',
  MODIFY COLUMN location_value VARCHAR(128) NULL COMMENT '阅读定位值，小说可存段落偏移、漫画可存页码',
  MODIFY COLUMN client_type VARCHAR(32) NULL COMMENT '客户端类型：H5、MP_WEIXIN、APP等',
  MODIFY COLUMN read_at DATETIME NULL COMMENT '阅读发生时间',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE reader_reading_progress COMMENT = '阅读进度表';
ALTER TABLE reader_reading_progress
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '阅读进度ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '作品ID',
  MODIFY COLUMN content_type VARCHAR(16) NOT NULL COMMENT '内容类型：NOVEL小说、COMIC漫画',
  MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '当前章节ID',
  MODIFY COLUMN location_value VARCHAR(128) NULL COMMENT '阅读定位值，小说可存段落偏移、漫画可存页码',
  MODIFY COLUMN progress_percent INT NOT NULL DEFAULT 0 COMMENT '阅读进度百分比',
  MODIFY COLUMN client_type VARCHAR(32) NOT NULL COMMENT '最近写入进度的客户端类型',
  MODIFY COLUMN progress_updated_at DATETIME NOT NULL COMMENT '最近一次进度更新时间',
  MODIFY COLUMN create_dept BIGINT(20) NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT(20) NULL COMMENT '创建人',
  MODIFY COLUMN create_time DATETIME NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT(20) NULL COMMENT '更新人',
  MODIFY COLUMN update_time DATETIME NULL COMMENT '更新时间';
